name: github pages

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      # - name: Build Preview
      #   run: hugo --minify --baseURL https://www-preview.openstreetmap.de/

      # - name: Deploy Preview
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     cname: www-preview.openstreetmap.de

      - name: Build
        run: hugo --minify
          
      - name: Deploy site
        if: github.ref == 'refs/heads/main'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${SSH_KEY}"
          rsync --exclude=/w --delete -r -e "ssh -o StrictHostKeyChecking=no -p 22" public/ web@web2.fossgis.de:/
